databases:
  - name: saints_feed
    databaseName: saints_feed_production
    user: saints_feed
    plan: starter

services:
  - type: web
    name: saints_feed
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    preDeployCommand: "bundle exec rails db:migrate"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: saints_feed
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
  - type: worker
    name: scrapers
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: saints_feed
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
