databases:
  - name: saints_feed
    databaseName: saints_feed_production
    user: saints_feed
    plan: starter

services:
  - type: web
    name: saints_feed
    runtime: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec puma"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: saints_feed
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
  - type: worker
    name: scrapers
    runtime: ruby
    plan: starter
    buildCommand: bundle install
    startCommand: bundle exec rake solid_queue:start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: saints_feed
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
