default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        pull_hampshire_live_articles:
          class: PullArticlesJob
          args: hampshire_live
          schedule: "*/5 * * * *"
        pull_southampton_fc_articles:
          class: PullArticlesJob
          args: southampton_fc
          schedule: "*/5 * * * *"
        pull_daily_echo_articles:
          class: PullArticlesJob
          args: daily_echo
          schedule: "*/5 * * * *"
  workers:
    - queues: "*"
      threads: 5
      processes: 1
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
